language: C
dist: trusty
sudo: required
env:
      global:
              - XC32_URL="http://ww1.microchip.com/downloads/en/DeviceDoc/xc32-v1.34-full-install-linux-installer.run"
                    - XC32_PATH="/opt/microchip/xc32/v1.34/bin"
                          - XC32_DL="$HOME/xc32.run"

      before_install:
            sudo dpkg --add-architecture i386 && sudo apt-get update
                  && sudo apt-get install libc6:i386 && wget -O "$XC32_DL" "$XC32_URL"
                        && chmod +x "$XC32_DL"
                              && sudo "$XC32_DL" --mode unattended --netservername localhost
                                    && export PATH="$PATH:$XC32_PATH";

      script:
            - xc32-gcc -mprocessor=32MX170F256B -I. -o main main.c
